services:
  nginx:
    image: nginx:latest
    container_name: rnapdbee-nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - adapters
